---
name: Release

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - v*

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Packages Container registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Container Reference Name
        id: container_ref
        run: |
          # Strip git ref prefix from version
          NAME=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,; s/^v//')
          # Use Docker `latest` tag convention
          [ "$NAME" == "master" ] && NAME=latest
          # Expose variables
          echo "::set-env name=name::$NAME"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer/
          push: true
          tags: ${{ github.repository }}:${{ env.ref_name }}
